trigger: none

pr: none

# Manually triggered — references CI to allow picking a specific CI run
resources:
  pipelines:
    - pipeline: ci
      source: JG-WeatherHistory.ci
      trigger: none

pool:
  name: Default

variables:
  - template: variables/vars-test.yml
  - group: jg-weatherhistory-secrets-t  # Must contain: subscriptionId, sqlAdminLogin, sqlAdminPassword

stages:
  - stage: DeployTest
    displayName: Deploy to Test
    jobs:
      - template: templates/template-deploy-all.yml
        parameters:
          appName: $(appName)
          environment: $(environment)
          location: $(location)
          serviceConnection: $(serviceConnection)
          paramsFile: $(paramsFile)
